Silence error in after case
Error was:
An error occurred in an after(:all) hook.
  NoMethodError: undefined method `each' for nil:NilClass
    occurred at
    /repos/dor-services/spec/dor/technical_metadata_service_spec.rb:54:in
    `block (2 levels) in <top (required)>'